[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gaian = "399QaMKHd7E8n8kQ9R7HoCN41cdSRnxwBCj89s2fDsw4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
