[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gaian = "EZ6wxSVyZgHGSNhg63hh8X9sovbugPMHJ5pG6ntyWQ1x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
